language: python
python:
  - "3.5"
notifications:
  email:
    on_success: never
    on_failure: never
  slack: huckley:ytUtSUTirXUlxyM01XDNkgKR

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest

# command to run tests
script:
  - py.test monitor.py -v --color=yes --exitfirst --showlocals --durations=5

